### ISSUE TITLE
[PE-D][Tester D] Visual bug where tags overlap with student name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-1/tp#259] opened 2024-11-08 16:46 UTC
Steps to reproduce:

1. Add a student with 6 or more tags
2. Find this student using find command

![image.png](https://raw.githubusercontent.com/ty4g1/ped/main/files/8c4da5bc-5234-4a2d-8e55-73641b5a2fb9.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: ty4g1/ped#4

**Comment by S-K-Y-Light** [comment] 2024-11-10 00:56
Repeated the Steps as described. Unable to reproduce the bug.

**Comment by S-K-Y-Light** [comment] 2024-11-11 13:33
Closing Issue as Team is unable to replicate the bug.

**Closed as completed by S-K-Y-Light** 2024-11-11 13:33 UTC
